/**
 * The authoring guide handed to AI agents through the MCP server (tool
 * `get_markdown_guide`, resource `markdown-studio://guide`) and exported as an
 * Agent Skill (`skills/markdown-studio/SKILL.md`, generated by
 * `npm run build:skill`). Keep it self-contained: an agent should be able to
 * write a well-formatted document from this text alone.
 */

import { ARGUMENT_CATALOG } from './arguments.js';

export const GUIDE_VERSION = '1.3.0';

export const MARKDOWN_GUIDE = `# Writing Markdown for Markdown Studio

Markdown Studio renders GitHub-flavoured Markdown into print-ready PDFs (and standalone HTML).
Everything below renders correctly. Anything not listed here (LaTeX math, HTML layouts, YAML
front-matter, custom CSS) does **not**.

## Workflow

1. Read this guide once (you are doing that now).
2. Pick a starting point: \`list_templates\` → \`get_template\` gives you proven structure **and** matching design settings for reports, proposals, READMEs, meeting notes, invoices and résumés. If the source is a web page, call \`import_web_page\` with the URL instead — it returns clean Markdown, metadata and an analysis; never retype page content from memory.
3. Write the Markdown. One \`#\` title, \`##\` sections, short paragraphs, generous use of tables, callouts and code blocks.
4. Run \`analyze_markdown\` — it returns the outline plus warnings (skipped heading levels, code fences without a language, YAML front-matter, missing images, ragged tables…). Fix everything it reports.
5. If the user asked for a nice PDF, tell them the design knobs (theme, paper, TOC, cover, header/footer, fonts) and agree a \`settings\` object — the full argument list is at the end of this guide.
6. Render with \`render_pdf\` (or \`render_html\` for a quick look). Pass \`markdown\`, \`settings\`, optional \`assets\` and \`fileName\`.
7. **Open the PDF immediately** — save it, then show it inside the client's own inline surface (in Cursor: a canvas that embeds the PDF), never in an external viewer or browser, and without asking first. See *After rendering: open the PDF immediately* at the end of this guide.

## Document structure

- Exactly **one** \`# H1\` at the very top — it becomes the document title, the PDF file name, the \`{title}\` placeholder in headers/footers and the cover title.
- Use \`##\` for sections and \`###\` for sub-sections. Never skip a level (\`##\` → \`####\`). \`####\`–\`######\` exist but rarely help in print.
- Open with a one-paragraph summary right under the title (or a \`> [!IMPORTANT]\` callout for the key takeaway).
- Keep paragraphs to 2–4 sentences. Prefer a list or table over a paragraph that enumerates things.
- Do **not** write your own table of contents — enable \`settings.toc\` and it is generated from \`##\`/\`###\` headings with correct page anchors.
- Do **not** number headings by hand ("2.1 Scope") — enable \`settings.headingNumbers\`.
- Don't hard-wrap lines at 80 columns; one paragraph = one line. A single trailing double-space (or a backslash) forces a line break; otherwise a blank line separates paragraphs.
- Separate every block (heading, list, table, code fence, quote) from its neighbours with a blank line.

## Supported syntax

### Inline

\`**bold**\`, \`*italic*\`, \`***both***\`, \`~~strikethrough~~\`, \`\` \`inline code\` \`\`, \`[link text](https://example.com)\`, \`<https://bare.url>\`, footnote refs \`[^1]\`.
Inline HTML \`<kbd>Ctrl</kbd>+<kbd>S</kbd>\`, \`<mark>highlight</mark>\`, \`<sup>2</sup>\`, \`<sub>i</sub>\` and \`<br>\` are styled. Emoji (\`:tada:\` is **not** supported — paste the actual character 🎉) render as consistent colour glyphs.

### Lists

\`\`\`md
- Item
  - Nested item (indent two spaces)
1. Ordered
2. Ordered
   1. Nested ordered
- [ ] Open task
- [x] Done task (rendered with a check box and struck through)
\`\`\`

Lists may contain paragraphs, code blocks and tables when indented to the item's text column.

### Tables

Tables are the strongest tool for structured content: they get striped rows, a coloured header row and never break awkwardly.

\`\`\`md
| Metric | Q2 | Q3 | Change |
| --- | ---: | ---: | ---: |
| ARR | $12.4M | $14.6M | **+18%** |
\`\`\`

- Right-align numbers with \`---:\`, centre with \`:---:\`.
- Keep to ≤ 6 columns on portrait paper (≤ 9 on landscape); split wider data into several tables.
- Every row must have the same number of cells as the header. Escape literal pipes as \`\\|\`.
- A table with an empty header (\`|  |  |\`) is fine for key–value blocks (e.g. invoice "From / To").

### Code

\`\`\`\`md
\`\`\`ts title="src/greet.ts"
export const greet = (name: string) => \`Hello, \${name}!\`;
\`\`\`
\`\`\`\`

- Always give fences a language (\`ts\`, \`js\`, \`python\`, \`bash\`, \`json\`, \`yaml\`, \`sql\`, \`go\`, \`rust\`, \`java\`, \`csharp\`, \`html\`, \`css\`, \`diff\`, \`text\`, …). Use \`text\` for plain output.
- \`title="…"\` (or the shorthand \`\`\`js:app.js) adds a file-name tab above the block.
- Blocks up to ~28 lines are kept on one page; longer blocks flow across pages. Prefer several short blocks over one huge one.
- Use \`~~~\` or four back-ticks to fence Markdown that itself contains \`\`\`.

### Callouts

\`\`\`md
> [!NOTE]
> Neutral information.

> [!TIP]
> A helpful hint.

> [!IMPORTANT]
> The key takeaway — use for executive-summary style highlights.

> [!WARNING]
> Something that can go wrong.

> [!CAUTION]
> Irreversible or dangerous.
\`\`\`

Plain \`> quotes\` render as an accent-bordered blockquote; nested \`> >\` quotes are supported.

### Images and figures

\`\`\`md
![Alt text](https://example.com/chart.png)
*Figure 1 — an optional caption on the very next line becomes a real figure caption*

![Logo](asset:logo.png =160x)      ← width 160 px, height automatic
![Photo](https://…/photo.jpg =600x400)
\`\`\`

- A standalone image paragraph is rendered as a centred \`<figure>\`; the \`*italic*\` line right after it is the caption.
- Remote images must be publicly reachable over HTTPS; the renderer waits for them but gives up after a while. For anything you generate locally, pass it in \`assets\` as a data URL and reference it as \`asset:<name>\`.
- Images are limited to the text width; use \`=WIDTHx\` to make them smaller. Don't embed screenshots wider than ~1600 px.

### Diagrams (Mermaid)

\`\`\`\`md
\`\`\`mermaid title="Deployment flow"
flowchart LR
  A[Commit] --> B{CI green?}
  B -- yes --> C[Deploy]
  B -- no --> D[Fix]
\`\`\`
\`\`\`\`

\`flowchart\`, \`sequenceDiagram\`, \`gantt\`, \`classDiagram\`, \`stateDiagram-v2\`, \`erDiagram\`, \`pie\`, \`xychart-beta\`, \`timeline\` and \`mindmap\` all work. Keep diagrams under ~20 nodes so they stay legible on paper. The optional \`title\` becomes a caption.

### Footnotes

\`\`\`md
Revenue grew 18%.[^src]

[^src]: Internal finance report, Q3 2026.
\`\`\`

Footnotes are collected under a "Footnotes" divider at the end of the document.

### Page breaks

Put \`\\pagebreak\` (or \`<!-- pagebreak -->\`) on its own line, surrounded by blank lines, to force a new page. Or set \`settings.pageBreaks\` to \`"h1"\` / \`"h2"\` for automatic breaks before every H1 / H1+H2.

### Horizontal rule

\`---\` on its own line (with blank lines around it — directly under a text line it turns that line into a heading).

## Design settings

Pass a \`settings\` object to \`render_pdf\` / \`render_html\`. Every key is optional. The complete argument list (tools, nested \`settings\` fields, enums, defaults, prompts) is in **Relaying options to the user** below — use that list when explaining choices to a person. \`list_design_options\` returns the same enums as JSON.

\`\`\`json
{
  "theme": "corporate",
  "font": "inherit",
  "headingFont": "inherit",
  "fontSize": "md",
  "accentColor": "#0F4C81",
  "paperSize": "A4",
  "orientation": "portrait",
  "margins": "normal",
  "background": "none",
  "pageBreaks": "h1",
  "toc": true,
  "headingNumbers": true,
  "justify": false,
  "header": { "text": "{title}", "showDate": true },
  "footer": { "text": "Confidential", "pageNumbers": true, "pageNumberStyle": "n-of-total" },
  "cover": { "enabled": true, "title": "", "subtitle": "Quarterly review", "author": "Strategy team", "date": "Q3 2026", "showLogo": true },
  "logo": { "dataUrl": "data:image/png;base64,…", "position": "title-right", "size": "md" }
}
\`\`\`

### Choosing a theme

| Theme | Feel | Good for |
| --- | --- | --- |
| \`clean\` | Neutral sans-serif, blue accent | READMEs, docs, general |
| \`corporate\` | Navy headings, white-on-navy table headers | Business reports, decks-as-docs |
| \`editorial\` | Serif body, warm paper, Playfair headings | Proposals, essays, long-form |
| \`forest\` | Calm greens, Lora serif | Meeting notes, internal memos |
| \`mono\` | Pure black & white, Space Grotesk | Invoices, specs, anything to be printed in B/W |
| \`midnight\` | Dark slate page, light text | Screen-only PDFs, slides-like handouts |

Every nested field, enum, default and tool argument is listed at the end of this guide.

## Recipes

- **Branded running header** — set \`logo.position: "page-header"\`, \`logo.dataUrl\`, \`logo.aspect\` (image width / height), and \`header.text\` together. The logo and text are vertically centered with an 8px gap; logo-only and text-only headers have no extra gap. Header logos are 14px tall with width capped at 160px; \`logo.size\` applies to title placements. \`header.showDate\` adds the date on the right. Do not imitate a running header with a Markdown image or spaces.
- **Business report** — \`corporate\`, \`toc\`, \`headingNumbers\`, \`cover.enabled\`, \`header.text: "{title}"\`, \`footer.text: "Confidential"\`, \`pageBreaks: "h1"\`. Start with an *Executive summary* and a KPI table.
- **Proposal / statement of work** — \`editorial\`, cover off, header \`"Proposal — {title}"\`; sections Overview → Objectives → Scope (phases as \`###\`) → Timeline (mermaid \`gantt\`) → Investment table → Acceptance table with signature rows.
- **README / technical doc** — \`clean\`, \`toc\`; titled code blocks, an options table (\`Option | Type | Default | Description\`), \`> [!WARNING]\` for gotchas.
- **Meeting notes** — \`forest\`, \`header.showDate\`; Attendees line, Agenda (ordered list), Discussion (\`###\` per item), Decisions (✅/⏸ bullets), Action items (task list with **Owner** in bold and a due date).
- **Invoice** — \`mono\`, page numbers off, footer "Thank you for your business."; key–value table for From/To/Dates, items table with right-aligned amounts, totals table, payment details.
- **Résumé / CV** — \`clean\`, \`fontSize: "sm"\`, \`margins: "narrow"\`, page numbers off; name as H1, one-line contact row, \`##\` per section, \`###\` per role with an \`*italic*\` dates line.
- **Web page / article** — \`import_web_page\` first; \`editorial\` for long-form, \`clean\` + \`toc\` for docs; \`header.text\` = site name, page numbers on; keep the page title as the single H1, remove leftover "share"/"related" fragments, close with a *Source: <url>* footnote.

## Anti-patterns (these render badly)

- YAML front-matter (\`---\\ntitle: …\\n---\`) — turns into a horizontal rule and a stray heading. Put the title in \`# H1\` instead.
- LaTeX / MathJax (\`$x^2$\`, \`$$…$$\`) — printed literally. Write formulas in words or use \`<sup>\`/\`<sub>\`.
- Raw HTML for layout (\`<table>\`, \`<div style>\`, \`<center>\`, \`<style>\`, \`<script>\`) — unstyled or stripped. Use Markdown tables.
- Hand-written tables of contents or numbered headings when \`toc\` / \`headingNumbers\` can do it.
- Multiple \`# H1\` titles in one document (unless you intend chapter-style sections with \`pageBreaks: "h1"\`).
- Code fences without a language, or with a language for prose.
- Very wide tables (> 6 columns portrait) or giant images — they get squeezed.
- Hard-wrapped paragraphs and trailing double-spaces used as "formatting" — they create random line breaks.
- Emoji in \`header.text\` / \`footer.text\` — running heads use a print font without emoji glyphs.
- Relative image paths (\`./img/chart.png\`) — the renderer cannot see your file system; use HTTPS URLs or \`assets\`.

${ARGUMENT_CATALOG}
`;
